### ISSUE TITLE
Need a decentralized backend

### ISSUE THREAD

**Issue by othnielussher** [dhruvpatidar359/Fluttersnips#8]
Before one can contribute, it is mentioned in the `readme` to create a Cloud Firestore database. Does this mean that each fork will have a different set of recently added widgets?

**Comment by dhruvpatidar359** [comment]
your idea is good, but what if contributor want to test some things with the firebase firestore(like implementing other features or adding data to firestore) , they may disturb the original database ?

**Comment by othnielussher** [comment]
Okay, good point. Let's stick to the current implementation for the time being.
